jadwal/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'jadwal'

urlpatterns = [
    path('', views.jadwal, name='jadwal'),
    path('tambah/', views.tambah, name='tambah'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
    path('detail/<int:detail_id>', views.detail, name='detail'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.home, name='index'),
    path('story1/', views.story1, name='story1'),
    path('pendidikan/', views.pendidikan, name='pendidikan'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('kegiatan/', include('kegiatan.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

jadwal/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Schedule(models.Model):
    matkul = models.CharField(max_length = 100)
    dosen = models.CharField(max_length = 100)
    sks = models.PositiveIntegerField(default = 1)
    deskripsi = models.TextField()
    list_tahun = {
        ('2020/2021', '2020/2021'),
        ('2021/2022', '2021/2022'),
        ('2022/2023', '2022/2023'),
        ('2023/2024', '2023/2024'),
    }
    tahun = models.CharField(
        max_length=100,
        choices = list_tahun,
        default = '2020/2021',
    )
    list_semester = {
        ('Ganjil', 'Ganjil'),
        ('Genap', 'Genap'),
    }
    semester = models.CharField(
        max_length=100,
        choices = list_semester,
        default = ('Ganjil', 'Ganjil'),
    )
    ruang = models.CharField(max_length = 100)
    jadwal = models.CharField(max_length=100)

jadwal/forms.py
from django import forms
from .models import Schedule

class Schedule_Form(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = "__all__"
        labels = {
            'matkul' : 'Mata Kuliah',
            'dosen' : 'Dosen Pengajar',
            'sks' : 'SKS',
            'deskripsi' : 'Deskripsi',
            'tahun' : 'Tahun',
            'semester' : 'semester',
            'ruang' : 'Ruang',
            'jadwal' : 'Jadwal',
        }

jadwal/views.py
from django.shortcuts import render, redirect
from .forms import Schedule_Form
from .models import Schedule

# Create your views here.

def jadwal(request):
    schedule = Schedule.objects.all()

    context = {
        'all_schedule':schedule
    }
    return render(request, 'jadwal/jadwal.html', context)

def tambah(request):
    schedule_form = Schedule_Form(request.POST or None)
    if request.method == "POST":
        if schedule_form.is_valid():
            schedule_form.save()
            return redirect('jadwal:jadwal')
    context = {
        'schedule_form' : schedule_form
    }
    return render(request, 'jadwal/tambah.html', context)

def delete(request, delete_id):
    Schedule.objects.filter(id = delete_id).delete()
    return redirect('jadwal:jadwal')

def detail(request, detail_id):
    jenis = Schedule.objects.get(pk = detail_id)
    context = {'jenis': jenis}
    return render(request, 'jadwal/detail.html', context)

jadwal/templates/jadwal/detail.html
{% extends 'base.html' %} {% load static %} {% block meta %}

<title>Detail {{ jenis.matkul }}</title>
{% endblock meta %} {% block content %}
<div class="jumbotron text-center">
    <h1>{{ jenis.matkul }}</h1>
</div>

<div class="container">
    <div>
        <a type="button" href="{% url 'jadwal:jadwal' %}" class="btn btn-primary">Back</a>
    </div>
    <div>
        <table style="margin: 3rem 0;" class="table table-hover">
            <tbody>
                <tr>
                    <th scope="row">Dosen Pengajar</th>
                    <td>{{ jenis.dosen }}</td>
                </tr>
                <tr>
                    <th scope="row">Jumlah SKS</th>
                    <td>{{ jenis.sks }}</td>
                </tr>
                <tr>
                    <th scope="row">Deskripsi</th>
                    <td>{{ jenis.deskripsi }}</td>
                </tr>
                <tr>
                    <th scope="row">Tahun Ajaran</th>
                    <td>{{ jenis.tahun }}</td>
                </tr>
                <tr>
                    <th scope="row">Semester</th>
                    <td>{{ jenis.semester }}</td>
                </tr>
                <tr>
                    <th scope="row">Ruang Kelas</th>
                    <td>{{ jenis.ruang }}</td>
                </tr>
                <tr>
                    <th scope="row">Jadwal</th>
                    <td>{{ jenis.jadwal }}</td>
                </tr>
            </tbody>
        </table>
    </div>

</div>
{% endblock %}

jadwal/templates/jadwal/jadwal.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Jadwal Mata Kuliah</title>
{% endblock meta %} {% block content %}
<div class="jumbotron text-center">
    <h1>Jadwal Mata Kuliah</h1>
</div>
<div style="padding: 50px; padding-top: 20px;">
    <div style="padding-bottom: 20px;">
        <a type="button" href="{% url 'jadwal:tambah' %}" class="btn btn-primary">Tambah</a>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Mata Kuliah</th>
                <th scope="col">Dosen Pengajar</th>
                <th scope="col">SKS</th>
                <th scope="col">Ruang</th>
                <th scope="col">Jadwal</th>
                <th scope="col"> </th>
            </tr>
        </thead>
        <tbody>
            {% for jenis in all_schedule %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{jenis.matkul}}</td>
                <td>{{jenis.dosen}}</td>
                <td>{{jenis.sks}}</td>
                <td>{{jenis.ruang}}</td>
                <td>{{jenis.jadwal}}</td>
                <td>
                    <a class="btn btn-info" href="{% url 'jadwal:detail' jenis.id %}">Detail</a>
                    <a class="btn btn-danger" href="{% url 'jadwal:delete' jenis.id %}">Hapus</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
{% endblock %}

jadwal/templates/jadwal/tambah.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} {% block meta %}
<title>Tambah Jadwal</title>
{% endblock meta %} {% block content %}
<div class="jumbotron text-center">
    <h1>Tambahkan Jadwal</h1>
</div>

<div class="container">
    <form method="POST">
        {% csrf_token %} {{ schedule_form | crispy }}
        <div style="margin: 3rem 0;">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

{% endblock %}