main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.home, name='index'),
    path('story1/', views.story1, name='story1'),
    path('pendidikan/', views.pendidikan, name='pendidikan'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('kegiatan/', include('kegiatan.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.masuk, name='masuk'),
    path('signup/', views.daftar, name='daftar'),
    path('logout/', views.keluar, name='keluar'),
]

story9/models.py
from django.db import models

# Create your models here.

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def index(request):
    return render(request, 'story9/index.html')

def masuk(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('story9:index')
        else:
            return render(request, 'story9/login.html', {'response':'Username/Password yang anda masukkan salah'})
    return render(request, 'story9/login.html')

def daftar(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story9:masuk')
    return render(request, 'story9/signup.html', {'form' : form})

def keluar(request):
    request.session.flush()
    logout(request)
    return redirect('story9:index')

story9/templates/story9/base.html
<!doctype html> {%load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <style>
        body {
            font: 400 15px Lato, sans-serif;
            line-height: 1.8;
        }
        
        .jumbotron {
            background-color: #6ed3cf;
            color: #fff;
            padding: 100px 25px;
            font-family: Montserrat, sans-serif;
        }
        
        .navbar a,
        .navbar .navbar-brand {
            color: #fff !important;
            margin-bottom: 0;
            background-color: #6ed3cf;
            z-index: 9999;
            border: 0;
            font-size: 12px !important;
            line-height: 1.42857143 !important;
            letter-spacing: 3px;
            border-radius: 0;
            font-family: Montserrat, sans-serif;
        }
        
        .navbar-nav a:hover,
        .navbar a:hover {
            color: #f4511e !important;
            background-color: #fff !important;
        }
    </style>
    {% block meta %} {% endblock %}
</head>

<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background: #6ed3cf">
        <a class="navbar-brand ml-5 px-3" href="{% url 'main:home' %}"> SR </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    			<span class="navbar-toggler-icon"></span>
  			</button>
        <div class="collapse navbar-collapse navbar-right" id="navbarNavAltMarkup">
            <div class="navbar-nav navbar-right px-5 ml-auto">
                <a class="nav-item nav-link px-3 h5" href="{% url 'story9:index' %}">Home</a> {% if user.is_authenticated %}
                <a class="nav-item nav-link px-3 h5" href="{% url 'story9:keluar' %}">Logout</a> {% else %}
                <a class="nav-item nav-link px-3 h5" href="{% url 'story9:masuk' %}">Login</a> {% endif %}
            </div>
        </div>
    </nav>

    {% block content %} {% endblock %}

</body>

</html>

story9/templates/story9/index.html
{% extends 'story9/base.html' %} {% load static %} {% block meta %}
<title>Story 9</title>
{% endblock meta %} {% block content %} {% if user.is_authenticated %}
<div class="jumbotron text-center">
    <h1>SELAMAT DATANG</h1>
    <h1>{{user.get_username}}</h1>
</div>
{% else %}
<div class="container text-center pt-4">
    <h3>Silahkan <a href="{% url 'story9:masuk' %}">Login</a> terlebih dahulu</h3>
</div>
{% endif %} {% endblock %}

story9/templates/story9/login.html
 {% load static %} {% block meta %}
<title>Login</title>
{% endblock meta %} {% block style %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css"> {% endblock %} {% block content %}

<div>
    <a type="button" href="{% url 'story9:index' %}" class="btn btn-info" style="margin: 10px;">Back</a>
</div>
<div class="login-reg-panel">
    <div class="info">
        <div class="register-info-box">
            <h2>Belum memiliki akun?</h2>
            <p>Yuk daftar dulu...</p>
            <div class="change">
                <a href="{% url 'story9:daftar' %}">
                    <label id="label-login" for="log-reg-show">Signup</label>
                    <input type="button" name="active-log-panel" id="log-reg-show">
                </a>
            </div>
        </div>
    </div>

    <div class="white-panel">
        <form method="post">
            {% csrf_token %}
            <div class="login-show">
                <h2>LOGIN</h2>
                <div class="form-group">
                    <input type="text" placeholder="Username" class="form-control" name="username" id="username" autocomplete="username">
                </div>
                <div class="form-group">
                    <input type="password" placeholder="Password" class="form-control" name="password" id="password" autocomplete="password">
                </div>
                <p>{{response}}</p>
                <button type="submit" class="btn btn-success" id="login">Login</button>
            </div>
        </form>
    </div>
</div>

{% endblock %} {% block js %}

<script>
    $(document).ready(function() {
        $('.login-info-box').fadeOut();
        $('.login-show').addClass('show-log-panel');
    });
</script>
{% endblock js %}

story9/templates/story9/signup.html
{% load static %} {% block meta %}
<title>Signup</title>
{% endblock meta %} {% block style %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css"> {% endblock %} {% block content %}

<div>
    <a type="button" href="{% url 'story9:index' %}" class="btn btn-info" style="margin: 10px;">Back</a>
</div>
<div class="all-reg-panel">
    <div class="info">
        <div class="login-info-box">
            <h2>Sudah memiliki akun?</h2>
            <p>Silahkan Login</p>
            <div class="change">
                <a href="{% url 'story9:masuk' %}">
                    <label id="label-register" for="log-reg-show">Login</label>
                    <input type="button" name="active-log-panel" id="log-reg-show">
                </a>
            </div>
        </div>
    </div>

    <div class="register-panel">
        <form method="post">
            {% csrf_token %}
            <div class="register-show">
                <h2>SIGNUP</h2>
                <table class="table table-sm">
                    {{ form.as_table }}
                </table>
                <a href="{% url 'story9:masuk' %}">
                    <button class="btn btn-success" id="daftar">Register</button>
                </a>
            </div>
        </form>
    </div>
</div>

{% endblock %} {% block js %}

<script>
    $(document).ready(function() {
        $('.register-info-box').fadeOut();
        $('.register-show').addClass('show-log-panel');
    });
</script>

{% endblock js %}