jadwal/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'jadwal'

urlpatterns = [
    path('', views.jadwal, name='jadwal'),
    path('tambah/', views.tambah, name='tambah'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
    path('detail/<int:detail_id>', views.detail, name='detail'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.home, name='index'),
    path('story1/', views.story1, name='story1'),
    path('pendidikan/', views.pendidikan, name='pendidikan'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('kegiatan/', include('kegiatan.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.story7, name='story7'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.story8, name='story8'),
    path('data/', views.data, name='data'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.masuk, name='masuk'),
    path('signup/', views.daftar, name='daftar'),
    path('logout/', views.keluar, name='keluar'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/index.html')

def pendidikan(request):
    return render(request, 'main/pendidikan.html')

def story1(request):
    return render(request, 'main/story1.html')

main/templates/main/header.html
 {% load static %}
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>                        
</button>
            <a class="navbar-brand" href="/">SR</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/#about">Profil</a></li>
                <li><a href="/#pengalaman">Pengalaman</a></li>
                <li><a href="{% url 'main:pendidikan' %}">Pendidikan</a></li>
                <li><a href="{% url 'main:story1' %}">Story 1</a></li>
                <li><a href="{% url 'jadwal:jadwal' %}">Jadwal Kuliah</a></li>
                <li><a href="{% url 'kegiatan:kegiatan' %}">Kegiatan</a></li>
                <li><a href="{% url 'story7:story7' %}">Story 7</a></li>
                <li><a href="{% url 'story8:story8' %}">Buku</a></li>
                <li><a href="{% url 'story9:index' %}">Story 9</a></li>
                <li><a href="#contact">Kontak</a></li>
            </ul>
        </div>
    </div>
</nav>

main/templates/main/index.html
{% extends 'base.html' %} {% block content %}
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sonia Rahmawati</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

</head>

<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">


    <div class="jumbotron text-center">
        <h1>SELAMAT DATANG</h1>
    </div>

    <div id="about" class="container-fluid">
        <div class="row">
            <div class="col">
                <h2 class="judul">PROFIL</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <h4>Tentang Saya</h4>
                <table class="saya">
                    <tr>
                        <td>Saya adalah mahasiswa Ilmu Komputer UI 2019. Saya berasal dari Sumatera Barat. Saya diterima di Ui melalui jalur SIMAK. Kuliah di jurusan ini adalah impian saya sejak lama. Saya berharap bisa mendapat ilmu dan pengalaman sebanyak
                            - banyaknya selama kuliah di sini.</td>
                    </tr>
                </table>

            </div>
            <div class="col-sm-4">
                <img src="{% static 'img/KR51.jpg' %}" alt="" width="250" height="360">
            </div>
            <div class="col-sm-4">
                <h4>Biodata</h4>
                <table class="bio">
                    <tr>
                        <td>Nama</td>
                        <td>: Sonia Rahmawati</td>
                    </tr>
                    <tr>
                        <td>PTN</td>
                        <td>: Universitas Indonesia</td>
                    </tr>
                    <tr>
                        <td>Fakultas</td>
                        <td>: Ilmu Komputer</td>
                    </tr>
                    <tr>
                        <td>Jurusan</td>
                        <td>: Ilmu Komputer</td>
                    </tr>
                    <tr>
                        <td>Angkatan</td>
                        <td>: 2019</td>
                    </tr>
                    <tr>
                        <td>NPM</td>
                        <td>: 1906398654</td>
                    </tr>
                    <tr>
                        <td>Hobi</td>
                        <td>: Nonton</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div id="pengalaman" class="container-fluid">
        <div class="row">
            <div class="col">
                <h2 class="judul">Pengalaman</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-7">
                <h4>Organisasi</h4>
                <ul>
                    <li>KIR (Kelompok Ilmiah Remaja)
                    </li>
                    <p>2016-2017</p>
                    <li>FUKI (Forum Ukhuwah Islamiah)
                    </li>
                    <p>2020-sekarang</p>
                </ul>
                <h4>Kepanitiaan</h4>
                <ul>
                    <li>Compfest 12 (Staf Software Engineering Academy)</li>
                    <p>2020-sekarang</p>
                    <li>KGTK Imami UI (Staf Simulasi SBMPTN)</li>
                    <p>2020-sekarang</p>
                </ul>
                <h4>Prestasi</h4>
                <ul>
                    <li>Juara 3 OSK Matematika SMA 2018</li>
                    <li>Juara 3 Lomba Matematika SMA di Universitas Bung Hatta 2017</li>
                    <li>Juara 1 Lomba Matematika SMA di STKIP YDB 2017</li>
                </ul>
            </div>
            <div class="col">
                <img src="{% static 'img/sea.jpg' %}" alt="" width="360" height="240"><br><br>
                <img src="{% static 'img/fuki.jpeg' %}" alt="" width="360" height="240">
            </div>
        </div>
    </div>


</body>

</html>
{% endblock %}

main/templates/main/kontak.html
{% load static %}
<div id="contact" style="background-color: #036c8b;">
    <div class="row">
        <div class="col">
            <h2 class="judul3">Kontak</h2>
            <div class="kontak">
                <a href="https://facebook.com/soniarahma27" class="link facebook" target="_parent"><span class="fa fa-facebook-square"></span></a>
                <a href="https://www.linkedin.com/in/soniarahmawati/" class="link linkedin" target="_parent"><span class="fa fa-linkedin"></span></a>
                <a href="https://www.instagram.com/sonia_rahma27/" class="link instagram" target="_parent"><span class="fa fa-instagram"></span></a>
            </div>
        </div>
    </div>
</div>

main/templates/main/pendidikan.html
{% extends 'base.html' %} {% block content %}
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pendidikan</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
</head>

<body>

    <div class="jumbotron text-center">
        <h1>Pendidikan</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <center>
                    <h3>SD</h3>
                    <img src="{% static 'img/sd.png' %}" alt="" width="180" height="190">
                    <h4>SD Negeri 11 Enam Lingkung</h4>
                    <p>(2007-2013)</p>
                </center>
            </div>
            <div class="col-sm-3">
                <center>
                    <h3>SMP</h3>
                    <img src="{% static 'img/smp.jpg' %}" alt="" width="180" height="190">
                    <h4>SMP Negeri 2 Enam Lingkung</h4>
                    <p>(2013-2016)</p>
                </center>
            </div>
            <div class="col-sm-3">
                <center>
                    <h3>SMA</h3>
                    <img src="{% static 'img/smanla.png' %}" alt="" width="180" height="190">
                    <h4>SMA Negeri 1 Lubuk Alung</h4>
                    <p>(2016-2019)</p>
                </center>
            </div>
            <div class="col-sm-3">
                <center>
                    <h3>Perguruan Tinggi</h3>
                    <img src="{% static 'img/MakaraUI.png' %}" alt="" width="180" height="190">
                    <h4>Universitas Indonesia</h4>
                    <p>(2019-sekarang)</p>
                </center>
            </div>
        </div>
    </div>

</body>

</html>
{% endblock %}

main/templates/main/story1.html
 {% block content %}
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Profil</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/story1.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
    <div class="container">
        <div class="class1">
            <div class="image">
                <img src="{% static 'img/KR51.jpg' %}" alt="" width="120" height="170">
            </div>
            <div class="teks">
                <h1>Sonia Rahmawati</h1>
                <h2>1906398654</h2>
                <h2>Ilmu Komputer 2019</h2>
            </div>
        </div>
        <div>
            <div>
                <div class="bio">
                    <h3>Halo!!!</h3>
                    <p>Saya Sonia Rahmawati, biasa dipanggil Sonia. Saya berasal dari Sumatera Barat. Saya merupakan mahasiswa Ilmu Komputer Fasilkom UI 2019. Saya diterima di UI jalur SIMAK. Saya memiliki hobi nonton.
                    </p>
                </div>
                <div>
                    <h3>Riwayat Pendidikan</h3>
                    <table>
                        <tr>
                            <th>Pendidikan</th>
                            <th>Sekolah/PTN</th>
                            <th>Tahun</th>
                        </tr>
                        <tr>
                            <td>SD</td>
                            <td>SDN 11 Enam Lingkung</td>
                            <td>2007-2013</td>
                        </tr>
                        <tr>
                            <td>SMP</td>
                            <td>SMPN 2 Enam Lingkung</td>
                            <td>2013-2016</td>
                        </tr>
                        <tr>
                            <td>SMA</td>
                            <td>SMAN 1 Lubuk Alung</td>
                            <td>2016-2019</td>
                        </tr>
                        <tr>
                            <td>PTN</td>
                            <td>Universitas Indonesia</td>
                            <td>2019 - sekarang</td>
                        </tr>
                    </table>
                </div>
            </div>

            <div class="social">
                <a href="https://facebook.com/soniarahma27" class="link facebook" target="_parent"><span class="fa fa-facebook-square"></span></a>
                <a href="https://www.linkedin.com/in/soniarahmawati/" class="link linkedin" target="_parent"><span class="fa fa-linkedin"></span></a>
                <a href="https://www.instagram.com/sonia_rahma27/" class="link instagram" target="_parent"><span class="fa fa-instagram"></span></a>
            </div>

        </div>
    </div>
</body>

</html>
{% endblock %}