kegiatan/urls.py
from django.urls import path
from . import views

app_name = 'kegiatan'

urlpatterns = [
    path('', views.kegiatan, name='kegiatan'),
    path('tambah/', views.tambah, name='tambah'),
    path('peserta/<int:index>/', views.peserta, name='peserta'),
    path('deleteKegiatan/<int:delete_id>', views.deleteKegiatan, name='deleteKegiatan'),
    path('deletePeserta/<int:delete_id>', views.deletePeserta, name='deletePeserta'),
    path('detail/<int:detail_id>/', views.detail, name='detail'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.home, name='index'),
    path('story1/', views.story1, name='story1'),
    path('pendidikan/', views.pendidikan, name='pendidikan'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('kegiatan/', include('kegiatan.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

kegiatan/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length = 100)
    deskripsi = models.TextField()
    tanggal = models.CharField(max_length=100)

    def __str__(self):
        return self.nama_kegiatan

class Peserta(models.Model):
    nama = models.CharField(max_length=100)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, null= True)

    def __str__(self):
        return self.nama

kegiatan/forms.py
from django import forms
from .models import Kegiatan, Peserta
# Create your views here.

class Kegiatan_Form(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = "__all__"
        labels = {
            'nama_kegiatan' : 'Kegiatan',
            'nama_peserta' : 'Nama',
            'deskripsi' : 'Deskripsi Kegiatan',
            'tanggal': 'Tanggal Kegiatan',
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})
class Peserta_Form(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = ['nama']
        labels = {'nama' : 'Nama Peserta'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})

kegiatan/views.py
from django.shortcuts import render, redirect
from .forms import Kegiatan_Form, Peserta_Form
from .models import Kegiatan, Peserta
# Create your views here.

def kegiatan(request):
    all_activity = Kegiatan.objects.all()
    context = {
        'all_activity':all_activity
    }
    return render(request, 'kegiatan/kegiatan.html', context)

def tambah(request):
    kegiatan_form = Kegiatan_Form(request.POST or None)
    if request.method == "POST":
        if kegiatan_form.is_valid():
            kegiatan_form.save()
        return redirect('kegiatan:kegiatan')
    
    context = {
        'kegiatan_form' : kegiatan_form
    }
    return render(request, 'kegiatan/tambah.html', context)

def peserta(request, index):
    peserta_form = Peserta_Form(request.POST or None)
    if request.method == "POST":
        if peserta_form.is_valid():
            peserta = Peserta(kegiatan=Kegiatan.objects.get(pk = index), nama=peserta_form.data['nama'])
            peserta.save()
        x = '/kegiatan/detail/' + str(index)
        return redirect(x)
    
    context = {
        'peserta_form' : peserta_form
    }
    return render(request, 'kegiatan/peserta.html', context)

def deleteKegiatan(request, delete_id):
    Kegiatan.objects.filter(id = delete_id).delete()
    return redirect('kegiatan:kegiatan')

def deletePeserta(request, delete_id):
    p = Peserta.objects.get(pk = delete_id)
    p.delete()
    x = '/kegiatan/detail/' + str(p.kegiatan.id)
    return redirect(x)

def detail(request, detail_id):
    jenis = Kegiatan.objects.get(pk = detail_id)
    semua_peserta = Peserta.objects.filter(kegiatan = jenis)
    return render(request, 'kegiatan/detail.html', {'jenis': jenis, 'semua_peserta':semua_peserta})

kegiatan/templates/kegiatan/detail.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Detail {{ jenis.nama_kegiatan }}</title>
{% endblock meta %} {% block content %}
<div class="jumbotron text-center">
    <h1>{{ jenis.nama_kegiatan }}</h1>
</div>
<div>
    <div class="container">
        <table style="margin: 3rem 0; text-align: center;" class="table table-hover">
            <tbody>
                <tr>
                    <th scope="row" style="text-align: center;">Tanggal Kegiatan</th>
                </tr>
                <tr>
                    <td>{{ jenis.tanggal }}</td>
                </tr>
                <br>
                <tr>
                    <th scope="row" style="text-align: center;">Deskripsi</th>
                </tr>
                <tr>
                    <td>{{ jenis.deskripsi }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="container">
        <h1 style="text-align: center;">Peserta</h1>
        <table style="margin: 3rem 0; display: flex; justify-content: center;" class="table table-borderless">
            <tbody>
                {% for peserta in semua_peserta %}
                <tr>
                    <th>{{peserta.nama}}</th>
                    <td><a class="btn btn-danger" href="{% url 'kegiatan:deletePeserta' peserta.id %}">Hapus</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="jumbotron" style="background-color: white; text-align: center;">
        <a type="button" href="{% url 'kegiatan:kegiatan' %}" class="btn btn-primary">Back</a>
        <a class="btn btn-primary" href="{% url 'kegiatan:peserta' jenis.id %}">Tambah</a>
    </div>

</div>

{% endblock %}

kegiatan/templates/kegiatan/kegiatan.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Kegiatan</title>
{% endblock meta %} {% block content %}
<div class="jumbotron text-center">
    <h1>Kegiatan</h1>
</div>

<div class="container">
    <div class="row row-cols">
        {% for jenis in all_activity %}
        <div class="col">
            <div class="jumbotron" style="padding: 30px;background-color: #89cada;">
                <h1 class="display-4" style="text-align: center;">{{ jenis.nama_kegiatan }}</h1>
                <hr class="my-4">
                <p class="text-align-center">{{ jenis.tanggal}}</p>
                <a class="btn btn-primary btn-lg" href="{% url 'kegiatan:detail' jenis.id %}" role="button">Detail</a>
                <a class="btn btn-danger btn-lg" href="{% url 'kegiatan:deleteKegiatan' jenis.id %}" role="button">Hapus</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="jumbotron" style="background-color: white;text-align: center;">
    <a class="btn btn-primary" href="{% url 'kegiatan:tambah' %}">Tambah</a>
</div>

{% endblock %}

kegiatan/templates/kegiatan/peserta.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} {% block meta %}
<title>Tambah Peserta</title>
{% endblock meta %} {% block content %}
<div class="jumbotron text-center">
    <h1>Tambahkan Peserta</h1>
</div>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group col">
            {{ peserta_form|crispy}}
        </div>
        <div class="jumbotron text-center" style="background-color: white;">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

{% endblock %}

kegiatan/templates/kegiatan/tambah.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} {% block meta %}
<title>Tambah Kegiatan</title>
{% endblock meta %} {% block content %}
<div class="jumbotron text-center">
    <h1>Tambahkan Kegiatan</h1>
</div>
<div class="container">
    <form method="POST">
        {% csrf_token %} {{ kegiatan_form|crispy}}
        <div class="jumbotron" style="background-color: white;">
            <a type="button" href="{% url 'kegiatan:kegiatan' %}" class="btn btn-primary">Back</a>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

{% endblock %}